#!/usr/bin/env python3
"""
article3_cfius_analysis.py

Article 3 empirical pipeline -- CFIUS counterfactual jurisdiction analysis.

Task 1: Build regime-tagged, geocoded CFIUS Appendix A site database
Task 2: Compute Haversine distances and classify AFIDA holdings as
        covered/not covered under each of four regulatory regimes

Inputs:
  - AFIDACurrentHoldingsYR2024.xlsx (from USDA FSA)
  - c_16ap26.zip (NOAA county centroids shapefile)
  - mirta-dod-sites-boundaries-geojson.geojson (DoD MIRTA installation boundaries)
  - cfius_appendix_a_all_regimes.csv (generated by build_cfius_db.py)

Outputs:
  - cfius_appendix_a_geocoded.csv (230 sites with coordinates and regime tags)
  - cfius_jurisdiction_analysis.csv (119 counties x 4 regimes)
  - cfius_headline_table.txt (summary statistics)

Sources:
  - 85 FR 3166 (Jan 17, 2020) -- Original Part 802 Appendix A
  - 88 FR 57348 (Aug 23, 2023) -- 8 installations added
  - 89 FR 88128 (Nov 7, 2024) -- 59 added, 8 moved, 3 removed
  - eCFR Title 31, Appendix A to Part 802 (current as of Jan 2026)
  - MIRTA DoD Sites Boundaries GeoJSON (DataLumos Project 239602)

Author: Robert J. Green | robert@rjgreenresearch.org
ORCID: 0009-0002-9097-1021
"""

from __future__ import annotations

import csv
import json
import math
import os
import sys
from collections import defaultdict
from difflib import SequenceMatcher
from typing import Dict, List, Optional, Tuple

try:
    import openpyxl
    import shapefile
except ImportError:
    print("Required: pip install openpyxl pyshp")
    sys.exit(1)


# ===================================================================
# CONFIGURATION
# ===================================================================

# Input paths (relative to project root: cfius-jurisdiction-analysis/)
AFIDA_PATH = "data/inputs/AFIDACurrentHoldingsYR2024.xlsx"
NOAA_SHAPEFILE = "data/inputs/c_16ap26"  # .shp/.dbf/.shx without extension
MIRTA_GEOJSON = "data/inputs/mirta-dod-sites-points-geojson.geojson"
APPENDIX_A_CSV = "data/outputs/cfius_appendix_a_all_regimes.csv"

# Output paths
OUTPUT_GEOCODED = "data/outputs/cfius_appendix_a_geocoded.csv"
OUTPUT_ANALYSIS = "data/outputs/cfius_jurisdiction_analysis.csv"
OUTPUT_HEADLINE = "data/outputs/cfius_headline_table.txt"

# Part 3 ICBM Missile Field Counties (31 CFR Part 802, Appendix A)
# Binary FIPS test -- no distance threshold. Present since Regime 2 (Feb 2020).
PART3_FIPS = {
    # 90th MW (F.E. Warren AFB) -- CO, NE, WY
    '08075','08087','08115','08121','08123',
    '31007','31033','31049','31069','31105','31123','31157','31165',
    '56015','56021','56031',
    # 341st MW (Malmstrom AFB) -- MT
    '30005','30013','30015','30027','30035','30037','30045','30049',
    '30051','30059','30065','30069','30071','30073','30095','30097',
    '30099','30101','30107',
    # 91st MW (Minot AFB) -- ND
    '38009','38013','38025','38049','38053','38055','38057','38061',
    '38069','38075','38083','38101','38105',
}


# ===================================================================
# HAVERSINE DISTANCE
# ===================================================================

def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in miles between two lat/lon points."""
    R = 3959  # Earth radius in miles
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) *
         math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) ** 2)
    return R * 2 * math.asin(math.sqrt(a))


# ===================================================================
# TASK 1: GEOCODE APPENDIX A SITES
# ===================================================================

# Manual coordinate overrides for sites not matched by MIRTA
MANUAL_COORDS: Dict[str, Tuple[float, float]] = {
    "Air Force Office of Scientific Research": (38.8803, -77.1066),
    "Anniston Army Depot": (33.7208, -85.8497),
    "Army Futures Command": (30.3891, -97.7244),
    "Army Research Lab--Orlando Simulations and Training Technology Center": (28.5861, -81.1975),
    "Biometric Technology Center (Defense Forensics and Biometrics Agency)": (39.3252, -80.2635),
    "Blue Grass Army Depot": (37.7019, -84.2177),
    "Camp Roberts": (35.7601, -120.7454),
    "Camp Grayling": (44.6614, -84.7282),
    "Camp Williams": (40.4398, -111.9282),
    "Defense Advanced Research Projects Agency": (38.8803, -77.1066),
    "Guam Tracking Station": (13.3733, 144.6897),
    "Hawthorne Army Depot": (38.5175, -118.6102),
    "Iowa Army Ammunition Plant": (40.8303, -91.1118),
    "Joint Base Anacostia-Bolling": (38.8415, -77.0128),
    "Joint Base Myer-Henderson Hall": (38.8765, -77.0808),
    "Joint Base San Antonio": (29.3842, -98.5811),
    "Joint Systems Manufacturing Center--Lima": (40.7157, -83.9932),
    "Lake City Army Ammunition Plant": (39.0503, -94.3789),
    "Letterkenny Army Depot": (39.9561, -77.6680),
    "Marine Corps Base Hawaii": (21.4505, -157.7498),
    "Marine Corps Logistics Base Albany": (31.5399, -84.0621),
    "Marine Corps Logistics Base Barstow": (34.8694, -116.9561),
    "McAlester Army Ammunition Plant": (34.8220, -95.9219),
    "Military Ocean Terminal Concord": (38.0038, -122.0609),
    "Military Ocean Terminal Sunny Point": (33.9606, -78.0066),
    "Naval Weapons Station Seal Beach Detachment Norco": (33.9372, -117.5711),
    "Pueblo Chemical Depot": (38.2697, -104.4528),
    "Red River Army Depot": (33.4461, -94.2988),
    "Romanzof Regional Radar Site": (61.7817, -166.0975),
    "Scranton Army Ammunition Plant": (41.3876, -75.6229),
    "Tooele Army Depot": (40.5131, -112.3875),
    "Chocolate Mountain Aerial Gunnery Range": (33.0247, -115.5456),
    "Fallon Range Complex": (39.4163, -118.7001),
    "Townsend Bombing Range": (31.5747, -81.3536),
    "Tropic Regions Test Center": (21.5067, -158.0031),
    "Iowa National Guard Joint Force Headquarters": (41.6005, -93.6091),
    "Lackland Air Force Base": (29.3842, -98.6177),
    "Marine Corps Support Facility Blount Island": (30.4060, -81.5325),
    "Barter Island Regional Radar Site": (70.1340, -143.6577),
    "Cold Bay Regional Radar Site": (55.2050, -162.7225),
    "Lisburne Regional Radar Site": (68.8752, -166.1100),
    "Marine Corps Air Station Cherry Point": (34.9009, -76.8806),
    "Tatalina Regional Radar Site": (62.8944, -155.9683),
    "West Desert Test Center": (40.1543, -113.2047),
    "Kotzebue Regional Radar Site": (66.8784, -162.6050),
}

# MIRTA name overrides (Appendix A name -> MIRTA feature name)
MIRTA_OVERRIDES: Dict[str, str] = {
    "Air Force Maui Optical and Supercomputing Site": "Remote Maui Experimental Site",
    "Combat Capabilities Development Command Soldier Center": "US Army Soldier Systems Center",
    "Joint Base Lewis-McChord": "Fort Lewis",
    "Joint Base McGuire-Dix-Lakehurst": "Dix",
    "Kaena Point Satellite Tracking Station": "Kaena Point Space Force Statio",
    "Marine Corps Air Ground Combat Center Twentynine Palms": "Twentynine Palms",
    "Naval Surface Warfare Center Carderock Division--Acoustic Research Detachment": "Bayview Idaho",
    "Pentagon": "Pentagon Building Site",
    "Portsmouth Naval Shipyard": "NSY Portsmouth",
    "Southeast Alaska Acoustic Measurement Facility": "Back Island AK",
    "Pacific Missile Range Facility": "CNIC PMRF Barking Sands HI",
    "Kodiak Tracking Station": "Kodiak AK",
    "Cape Cod Air Force Station": "Cape Cod Space Force Station",
    "Camp Dodge": "NG Camp Dodge Johnston TS",
}


def geocode_appendix_a(appendix_csv: str, mirta_path: str) -> List[dict]:
    """Geocode all Appendix A sites using MIRTA GeoJSON + manual overrides."""

    # Load all MIRTA features
    with open(mirta_path) as f:
        mirta = json.load(f)

    mirta_sites = []
    for feat in mirta["features"]:
        p = feat["properties"]
        geom = feat["geometry"]
        if geom["type"] == "Point":
            lon = geom["coordinates"][0]
            lat = geom["coordinates"][1]
        elif geom["type"] == "Polygon":
            coords = geom["coordinates"][0]
            lat = sum(c[1] for c in coords) / len(coords)
            lon = sum(c[0] for c in coords) / len(coords)
        elif geom["type"] == "MultiPolygon":
            largest = max(geom["coordinates"], key=lambda x: len(x[0]))
            coords = largest[0]
            lat = sum(c[1] for c in coords) / len(coords)
            lon = sum(c[0] for c in coords) / len(coords)
        else:
            continue
        mirta_sites.append({
            "name": (p.get("siteName") or "").strip(),
            "lat": round(lat, 6),
            "lon": round(lon, 6),
        })

    mirta_by_name = {s["name"]: s for s in mirta_sites}

    # Load Appendix A
    rows = []
    with open(appendix_csv) as f:
        for row in csv.DictReader(f):
            rows.append(row)

    results = []
    for a in rows:
        name = a["site_name"]
        lat = lon = ""
        match_name = ""

        # Priority 1: Manual coordinates
        if name in MANUAL_COORDS:
            lat, lon = MANUAL_COORDS[name]
            match_name = "MANUAL_COORDS"

        # Priority 2: MIRTA name override
        elif name in MIRTA_OVERRIDES:
            override = MIRTA_OVERRIDES[name]
            if override in mirta_by_name:
                m = mirta_by_name[override]
                lat, lon = m["lat"], m["lon"]
                match_name = override
            else:
                # Fuzzy match override name
                best_s, best_m = 0, None
                for s in mirta_sites:
                    sc = SequenceMatcher(None, override.lower(), s["name"].lower()).ratio()
                    if sc > best_s:
                        best_s, best_m = sc, s
                if best_m and best_s > 0.5:
                    lat, lon = best_m["lat"], best_m["lon"]
                    match_name = best_m["name"]

        # Priority 3: Auto fuzzy match
        else:
            def norm(s):
                return (s.lower().replace("air force base", "afb")
                        .replace("space force base", "sfb")
                        .replace("space force station", "sfs")
                        .replace("--", " ").replace("-", " ").strip())

            best_s, best_m = 0, None
            for s in mirta_sites:
                sc = SequenceMatcher(None, norm(name), norm(s["name"])).ratio()
                if sc > best_s:
                    best_s, best_m = sc, s
            if best_m and best_s >= 0.60:
                lat, lon = best_m["lat"], best_m["lon"]
                match_name = best_m["name"]

        results.append({
            "site_name": name,
            "location": a["location"],
            "current_part": a["current_part"],
            "threshold_miles": a["threshold_miles"],
            "regime_added": a["regime_added"],
            "latitude": lat,
            "longitude": lon,
            "conus": a["conus"],
            "mirta_match": match_name,
        })

    return results


# ===================================================================
# TASK 2: COUNTERFACTUAL JURISDICTION ANALYSIS
# ===================================================================

def sites_for_regime(sites: List[dict], regime: int) -> List[dict]:
    """Return sites active under a given regime with effective thresholds."""
    if regime == 1:
        return []

    result = []
    for s in sites:
        if not s["latitude"]:
            continue
        added = s["regime_added"]
        part = int(s["current_part"])

        if regime == 2:
            if added in ("2020", "2020_moved_2024"):
                threshold = 1 if added == "2020_moved_2024" else int(s["threshold_miles"])
                result.append({**s, "effective_threshold": threshold})
            elif added == "2020" and part == 0:
                result.append({**s, "effective_threshold": int(s["threshold_miles"])})

        elif regime == 3:
            if added in ("2020", "2020_moved_2024", "2023"):
                threshold = 1 if added == "2020_moved_2024" else int(s["threshold_miles"])
                result.append({**s, "effective_threshold": threshold})
            elif part == 0 and added in ("2020", "2023"):
                result.append({**s, "effective_threshold": int(s["threshold_miles"])})

        elif regime == 4:
            if part > 0:
                result.append({**s, "effective_threshold": int(s["threshold_miles"])})

    return result


def parse_afida_chinese(afida_path: str) -> List[dict]:
    """Parse Chinese-linked holdings from AFIDA 2024 Excel."""
    wb = openpyxl.load_workbook(afida_path, read_only=True)
    ws = wb.active

    holdings = []
    for row in ws.iter_rows(min_row=4, values_only=True):
        cells = [str(c).strip() if c else "" for c in row]
        if len(cells) < 11:
            continue
        country = cells[6]
        if "CHINA" not in country.upper() and "CHINESE" not in country.upper():
            continue
        try:
            acres = float(cells[10])
        except (ValueError, IndexError):
            continue
        if acres <= 0:
            continue

        fips = cells[2].replace(".0", "").strip().zfill(5)
        holdings.append({
            "state": cells[0],
            "county": cells[1],
            "fips": fips,
            "owner": cells[3],
            "country": country,
            "acres": acres,
        })

    wb.close()
    return holdings


def load_centroids(shapefile_path: str) -> Dict[str, Tuple[float, float]]:
    """Load NOAA county centroids from shapefile."""
    sf = shapefile.Reader(shapefile_path)
    fields = [f[0] for f in sf.fields[1:]]
    centroids = {}
    for rec in sf.records():
        fips = str(rec[fields.index("FIPS")]).strip()
        lat = float(rec[fields.index("LAT")])
        lon = float(rec[fields.index("LON")])
        centroids[fips] = (lat, lon)
    return centroids


def run_jurisdiction_analysis(
    holdings: List[dict],
    centroids: Dict[str, Tuple[float, float]],
    sites: List[dict],
) -> List[dict]:
    """Classify each county as covered/not covered under each regime."""

    # Aggregate by county
    county_data = {}
    for h in holdings:
        fips = h["fips"]
        if fips not in centroids:
            continue
        if fips not in county_data:
            lat, lon = centroids[fips]
            county_data[fips] = {
                "fips": fips, "county": h["county"], "state": h["state"],
                "lat": lat, "lon": lon, "entities": [], "total_acres": 0,
            }
        county_data[fips]["entities"].append(h["owner"])
        county_data[fips]["total_acres"] += h["acres"]

    results = []
    for fips, cd in county_data.items():
        row = {
            "fips": fips, "county": cd["county"], "state": cd["state"],
            "lat": cd["lat"], "lon": cd["lon"],
            "entity_count": len(cd["entities"]),
            "total_acres": round(cd["total_acres"], 1),
        }

        for regime in [1, 2, 3, 4]:
            active = sites_for_regime(sites, regime)
            min_dist = float("inf")
            nearest = None
            covered = False
            cov_site = cov_dist = cov_thresh = None

            for s in active:
                d = haversine(cd["lat"], cd["lon"],
                              float(s["latitude"]), float(s["longitude"]))
                if d < min_dist:
                    min_dist = d
                    nearest = s["site_name"]
                if d <= s["effective_threshold"] and not covered:
                    covered = True
                    cov_site = s["site_name"]
                    cov_dist = round(d, 1)
                    cov_thresh = s["effective_threshold"]

            row[f"r{regime}_covered"] = "Y" if covered else "N"
            row[f"r{regime}_nearest_site"] = nearest or "N/A"
            row[f"r{regime}_nearest_dist"] = round(min_dist, 1) if min_dist < float("inf") else "N/A"
            row[f"r{regime}_covering_site"] = cov_site or ""
            row[f"r{regime}_covering_dist"] = cov_dist or ""
            row[f"r{regime}_covering_threshold"] = cov_thresh or ""

            # Part 3: ICBM missile field county FIPS binary test
            # Present from Regime 2 onward (included in original 2020 rule)
            if regime >= 2 and not covered and fips in PART3_FIPS:
                row[f"r{regime}_covered"] = "Y"
                row[f"r{regime}_covering_site"] = "Part 3 ICBM county"
                row[f"r{regime}_covering_dist"] = 0
                row[f"r{regime}_covering_threshold"] = "county"

        results.append(row)

    return results


# ===================================================================
# MAIN
# ===================================================================

def main():
    print("=" * 70)
    print("Article 3: CFIUS Counterfactual Jurisdiction Analysis")
    print("=" * 70)

    # Check inputs exist
    # Auto-extract NOAA shapefile from zip if needed
    if not os.path.exists(NOAA_SHAPEFILE + ".shp") and os.path.exists(NOAA_SHAPEFILE + ".zip"):
        import zipfile
        print(f"Extracting {NOAA_SHAPEFILE}.zip...")
        with zipfile.ZipFile(NOAA_SHAPEFILE + ".zip") as zf:
            zf.extractall(os.path.dirname(NOAA_SHAPEFILE) or ".")
        print("  Done.")

    for path in [AFIDA_PATH, NOAA_SHAPEFILE + ".shp", MIRTA_GEOJSON, APPENDIX_A_CSV]:
        if not os.path.exists(path):
            print(f"ERROR: Required input not found: {path}")
            print("See script header for required input files.")
            print("Run from the project root: cd cfius-jurisdiction-analysis")
            sys.exit(1)

    # Task 1: Geocode
    print("\n--- Task 1: Geocoding Appendix A ---")
    geocoded = geocode_appendix_a(APPENDIX_A_CSV, MIRTA_GEOJSON)
    with open(OUTPUT_GEOCODED, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=geocoded[0].keys())
        w.writeheader()
        w.writerows(geocoded)
    n_geo = sum(1 for g in geocoded if g["latitude"])
    print(f"Geocoded: {n_geo} / {len(geocoded)} sites")

    # Task 2: Jurisdiction analysis
    print("\n--- Task 2: Jurisdiction Analysis ---")
    holdings = parse_afida_chinese(AFIDA_PATH)
    print(f"Chinese holdings: {len(holdings)}")

    # Save intermediate file for article3_complexity.py
    afida_intermediate = "data/outputs/afida_chinese_2024.csv"
    with open(afida_intermediate, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["fips", "county", "state", "owner", "country", "acres"])
        w.writeheader()
        w.writerows(holdings)
    print(f"Saved intermediate: {afida_intermediate}")

    centroids = load_centroids(NOAA_SHAPEFILE)
    print(f"County centroids: {len(centroids)}")

    results = run_jurisdiction_analysis(holdings, centroids, geocoded)
    print(f"Counties analyzed: {len(results)}")

    # Write results
    with open(OUTPUT_ANALYSIS, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=results[0].keys())
        w.writeheader()
        w.writerows(results)

    # Headline table
    total = len(results)
    total_acres = sum(r["total_acres"] for r in results)
    print(f"\n{'Regime':<10} {'Counties':>12} {'Rate':>8} {'Acreage':>14} {'Rate':>8}")
    print("-" * 55)
    for regime in [1, 2, 3, 4]:
        c = sum(1 for r in results if r[f"r{regime}_covered"] == "Y")
        a = sum(r["total_acres"] for r in results if r[f"r{regime}_covered"] == "Y")
        print(f"Regime {regime:<3} {c:>5}/{total:<4} {c/total*100:>6.1f}% {a:>12,.1f} {a/total_acres*100:>6.1f}%")

    # Save headline
    with open(OUTPUT_HEADLINE, "w") as f:
        f.write(f"Counties: {total} | Acreage: {total_acres:,.1f}\n")
        for regime in [1, 2, 3, 4]:
            c = sum(1 for r in results if r[f"r{regime}_covered"] == "Y")
            a = sum(r["total_acres"] for r in results if r[f"r{regime}_covered"] == "Y")
            f.write(f"Regime {regime}: {c}/{total} counties ({c/total*100:.1f}%), "
                    f"{a:,.1f} acres ({a/total_acres*100:.1f}%)\n")

    print(f"\nOutputs: {OUTPUT_GEOCODED}, {OUTPUT_ANALYSIS}, {OUTPUT_HEADLINE}")


if __name__ == "__main__":
    main()
